- name: delete default website
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent

- name: create html directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory

- name: download and extract frontend code
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
    dest: /usr/share/nginx/html
    remote_src: yes